# Generated by Django 3.2.16 on 2025-07-04 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование картриджа')),
                ('device_name', models.CharField(max_length=50, verbose_name='Наименование устройства')),
                ('acceptance_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ввода в эксп.')),
                ('decommissioning_date', models.DateTimeField(verbose_name='Дата вывода из эксп.')),
                ('inventory_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='инвентарный номер')),
                ('is_functional', models.BooleanField(default=True, null=True, verbose_name='рабочий')),
            ],
            options={
                'verbose_name': 'картридж',
                'verbose_name_plural': 'картриджи',
                'ordering': ('acceptance_date',),
            },
        ),
    ]
