# Generated by Django 3.2.16 on 2025-07-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0002_alter_cartridge_acceptance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='acceptance_date',
            field=models.DateField(verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='decommissioning_date',
            field=models.DateField(verbose_name='Дата ввода в эксп.'),
        ),
    ]
