# Generated by Django 3.2.16 on 2025-07-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0003_auto_20250704_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='decommissioning_date',
            field=models.DateField(null=True, verbose_name='Дата вывода из эксп.'),
        ),
    ]
