# Generated by Django 3.2.16 on 2025-07-10 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0005_alter_cartridge_decommissioning_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeCommissioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Место установки')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата ввода')),
                ('cartridge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cartridges.cartridge', verbose_name='Картридж')),
            ],
        ),
    ]
