# Generated by Django 3.2.16 on 2025-07-10 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0007_commissionedcartridge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionedcartridge',
            old_name='date',
            new_name='commission_date',
        ),
        migrations.RemoveField(
            model_name='commissionedcartridge',
            name='cartridge',
        ),
        migrations.AddField(
            model_name='commissionedcartridge',
            name='acceptance_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата получения'),
        ),
        migrations.AddField(
            model_name='commissionedcartridge',
            name='decommissioning_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата ввода в эксп.'),
        ),
        migrations.AddField(
            model_name='commissionedcartridge',
            name='device_name',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='Наименование устройства'),
        ),
        migrations.AddField(
            model_name='commissionedcartridge',
            name='inventory_number',
            field=models.IntegerField(default=0, verbose_name='инвентарный номер'),
        ),
        migrations.AddField(
            model_name='commissionedcartridge',
            name='is_functional',
            field=models.BooleanField(default=True, verbose_name='рабочий'),
        ),
        migrations.AddField(
            model_name='commissionedcartridge',
            name='name',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='Наименование картриджа'),
        ),
        migrations.AlterField(
            model_name='commissionedcartridge',
            name='location',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Место установки'),
        ),
    ]
